# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

sphinx:
   configuration: docs/source/conf.py

build:
  os: ubuntu-lts-latest
  apt_packages:
    - portaudio19-dev
    - supercollider
  tools:
    python: "3.12"

# Build all formats
formats: all

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
