name: ci

on:
  push:
    branches:
    - master
    - develop
  pull_request:
    branches:
    - master
    - develop
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Setup
        run: |
          python -m pip install tox tox-gh-actions
      - name: Run Linter
        run: |
          tox -e pre-commit,check-manifest
  test:
    strategy:
      matrix:
        python: [3.8, 3.9, 3.10, 3.11]
        platform: [ubuntu-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install SuperCollider
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
              sudo apt-get update
              sudo apt-get install --yes supercollider
              # start jack
              jackd --no-realtime -d dummy &
          elif [ "$RUNNER_OS" == "macOS" ]; then
              brew install --cask supercollider
          elif [ "$RUNNER_OS" == "Windows" ]; then
              # choco only offers an ancient version of SC.
              choco install supercollider
          fi
      - name: Install tox
        run: |
          python -m pip install tox tox-gh-actions
      - name: Run tests
        env:
          QT_DEBUG_PLUGINS: 1
        run: tox
